name: Deploy Frontend

on:
  push:
    branches:
      - 11.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2    
      # Clones the repository that triggered the workflow into the GitHub Actions runner
# Comments are added only for testing please remove the commands comments before use
    - name: automatic deployment
      # On repo settings > Secrets & Variables > Actions > New Repository Secrets then add the below secrets
      env:
         PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
         USER: ${{ secrets.EC2_USER }}
         HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "automatic deployment backend..."
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
        #   # Commands to execute on the EC2 instance
        #   cd /path/to/your/application
        # pull the new changes 
              echo "git pull origin 11.x.."
          # git pull origin 11.x  // actual shell script
          # run "php artisan migrate" to apply schema changes automatically
             echo "php artisan migrate --force..." 
          # php artisan migrate --force   // actual shell script
        EOF
        echo "Deployment complete!"
